/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

    import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;





/**
 *
 * @author João
 */
public class jficadastro extends javax.swing.JInternalFrame {
    
        private String Nome,dataCadastro,Endereco,Cidade,Email,Telefone,CPF,dataNascimento;

    /**
     * Creates new form jficadastro
     */
    public jficadastro() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_Cod = new javax.swing.JTextField();
        btn_Pesquisar = new javax.swing.JButton();
        jt_Dados = new javax.swing.JTabbedPane();
        jp_Dados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        texEnder = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        texCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        texEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ftexDataCadastro = new javax.swing.JFormattedTextField();
        ftexDataNascimento = new javax.swing.JFormattedTextField();
        ftexTelefone = new javax.swing.JFormattedTextField();
        texCPF = new javax.swing.JFormattedTextField();
        jp_Informaçoes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        texFormaçao_Profissional = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        texSalas_Atribuidas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_Naturalidade = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Professor");

        jLabel1.setText("Nome");

        jLabel2.setText("Cod.");

        btn_Pesquisar.setText("Pesquisar");

        jp_Dados.setBackground(new java.awt.Color(95, 148, 229));

        jLabel4.setText("Endereço (Rua, Bairro, Nº)");

        jLabel5.setText("Cidade/UF");

        jLabel6.setText("Nome Completo");

        jLabel3.setText("Data de Cadastro");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Email");

        jLabel9.setText("Telefone");

        jLabel14.setText("CPF (Somente Numero sem ponto, virgula ou traço)");

        try {
            ftexDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftexDataCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            ftexDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("  ##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftexDataNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            ftexTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#-########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftexTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftexTelefoneActionPerformed(evt);
            }
        });

        try {
            texCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jp_DadosLayout = new javax.swing.GroupLayout(jp_Dados);
        jp_Dados.setLayout(jp_DadosLayout);
        jp_DadosLayout.setHorizontalGroup(
            jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_DadosLayout.createSequentialGroup()
                        .addComponent(texEnder, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(texCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(369, Short.MAX_VALUE))
                    .addGroup(jp_DadosLayout.createSequentialGroup()
                        .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(texNome, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_DadosLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(ftexDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jp_DadosLayout.createSequentialGroup()
                                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_DadosLayout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_DadosLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(ftexTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jp_DadosLayout.createSequentialGroup()
                        .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(texCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftexDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jp_DadosLayout.setVerticalGroup(
            jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftexDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texEnder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftexTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(ftexDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jt_Dados.addTab("Dados Pessoais", jp_Dados);

        jLabel11.setText("      Formação Profissional");

        jLabel13.setText("Salas Atribuidas");

        javax.swing.GroupLayout jp_InformaçoesLayout = new javax.swing.GroupLayout(jp_Informaçoes);
        jp_Informaçoes.setLayout(jp_InformaçoesLayout);
        jp_InformaçoesLayout.setHorizontalGroup(
            jp_InformaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_InformaçoesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp_InformaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texSalas_Atribuidas, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(texFormaçao_Profissional, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(526, Short.MAX_VALUE))
            .addGroup(jp_InformaçoesLayout.createSequentialGroup()
                .addGroup(jp_InformaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_InformaçoesLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel12))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_InformaçoesLayout.setVerticalGroup(
            jp_InformaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_InformaçoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(texFormaçao_Profissional, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(texSalas_Atribuidas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jt_Dados.addTab("Informações", jp_Informaçoes);

        btn_Naturalidade.setText("Excluir");

        btn_Limpar.setText("Limpar");

        btn_Editar.setText("Editar");

        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Sair.setText("Sair");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jt_Dados)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tf_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Pesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Naturalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pesquisar))
                .addGap(18, 18, 18)
                .addComponent(jt_Dados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Naturalidade)
                    .addComponent(btn_Limpar)
                    .addComponent(btn_Editar)
                    .addComponent(btn_Cadastrar)
                    .addComponent(btn_Sair)))
        );

        setBounds(300, 20, 1041, 629);
    }// </editor-fold>//GEN-END:initComponents
        
    
    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        // TODO add your handling code here:
        jfPrincipal obj = new jfPrincipal();
    
        this.dispose();
    }//GEN-LAST:event_btn_SairActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
            Nome = texNome.getText();
            dataCadastro = ftexDataCadastro.getText();
            Endereco = texEnder.getText();
            Cidade = texCidade.getText();
            Email = texEmail.getText();
            Telefone = ftexTelefone.getText();
            dataNascimento = ftexDataNascimento.getText();
           
            CPF = texCPF.getText();
            
            
              try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/login","root","");
            Statement stm = con.createStatement();
            if(stm.executeUpdate("INSERT into professor(Nome,DataCadastro,DataNascimento,Email,Telefone,CPF,Cidade,Endereco) values('"+Nome+"','"+dataCadastro+"','"+dataNascimento+"','"+Email+"','"+Telefone+"','"+CPF+"','"+Cidade+"','"+Endereco+"')")!=0)
          {
                JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!!!","Sucesso",JOptionPane.INFORMATION_MESSAGE);
                        texNome.setText("");
                        ftexDataCadastro.setText("");
                        ftexDataNascimento.setText("");
                        texEnder.setText("");
                        texCidade.setText("");
                        texEmail.setText("");
                        ftexTelefone.setText("");
                       
                         texCPF.setText("");
                         
          }
            else
            {
                JOptionPane.showMessageDialog(null,"Erro para realizar o cadastro!!!","Erro",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void ftexTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftexTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftexTelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Naturalidade;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JFormattedTextField ftexDataCadastro;
    private javax.swing.JFormattedTextField ftexDataNascimento;
    private javax.swing.JFormattedTextField ftexTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jp_Dados;
    private javax.swing.JPanel jp_Informaçoes;
    private javax.swing.JTabbedPane jt_Dados;
    private javax.swing.JFormattedTextField texCPF;
    private javax.swing.JTextField texCidade;
    private javax.swing.JTextField texEmail;
    private javax.swing.JTextField texEnder;
    private javax.swing.JTextField texFormaçao_Profissional;
    private javax.swing.JTextField texNome;
    private javax.swing.JTextField texSalas_Atribuidas;
    private javax.swing.JTextField tf_Cod;
    private javax.swing.JTextField tf_Nome;
    // End of variables declaration//GEN-END:variables

    private void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
